# NOTE: bizarrely, the SHA256 sum reported in the conda-forge CI systems is
# different than what I compute if I download the file myself. But I get the
# same value if I run the build in a Docker container on my laptop, so I guess
# conda-build is somehow computing the digest weirdly. As far as I can tell,
# the file is actually downloaded fine, so I'm just using the weird value that
# conda-build derives. This started happening with version 3.430; maybe it
# will go away in future versions? -- @pkgw, 2018 Mar 7.

{% set name = "cfitsio" %}
{% set version = "3.430" %}
{% set nodotversion = version | replace('.', '') %}
{% set sha256 = "45665dd34cfe8ceef8bd718380d6018e5690f097420ca504d9152ae98696efd3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/{{ name }}{{ nodotversion }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - ldflags.patch
    - mac_64only.patch

build:
  number: 1001
  detect_binary_files_with_prefix: true
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - curl
  run:
    - curl

test:
  commands:
    - test -f ${PREFIX}/lib/libcfitsio.so  # [linux]
    - test -f ${PREFIX}/lib/libcfitsio.dylib  # [osx]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://heasarc.gsfc.nasa.gov/fitsio/fitsio.html
  license: fitsio
  license_file: License.txt
  summary: "A library for reading and writing FITS files"

extra:
  recipe-maintainers:
    - pkgw
