{% set version = "0.77" %}

package:
    name: astrometry.net
    version: {{ version }}

source:
    fn: astrometry-{{ version }}.zip
    url: https://github.com/dstndstn/astrometry.net/archive/{{ version }}.zip

build:
    number: 1
    skip: True # [osx]
    skip: True # [win]

requirements:
    build:
        - swig
        - {{ compiler('c') }}
        - git
        - make
        - {{ cdt('libx11-devel') }}          # [linux]
        - {{ cdt('libxau-devel') }}          # [linux]
        - {{ cdt('libxext-devel') }}         # [linux]
        - {{ cdt('libxrender-devel') }}      # [linux]
        - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
        - zlib
        - jpeg
        - netpbm
        - libpng
        - cfitsio
        - astropy
        - numpy
        - bzip2
        - cairo
    run:
        - zlib
        - jpeg
        - netpbm
        - libpng
        - cfitsio
        - astropy
        - numpy
        - bzip2
        - cairo

about:
    home: http://astrometry.net/
    license: BSD-like
    summary: Automatic recognition of astronomical images; or standards-compliant astrometric metadata from data.
